/* eslint-disable max-lines */
import { ITestUnitsMap } from '../types/test.units.types';
import { ITestCase } from '../types/types';

export const netVote = (units: ITestUnitsMap): ITestCase[] => [
  {
    title: 'Test VOTES IN NET 1 over WS',
    dbDataFile: 'restore.sh',
    connection: 'ws',
    connCount: 7,
    caseUnits: [ //                           01  02
      [units.account.login.user(1), 0], //     x   0
      [units.account.login.user(2), 1], //     1   x
      [units.account.login.user(3), 2], //     3   3
      [units.account.login.user(4), 3], //     5   5
      [units.account.signup.user(5), 4], //    0   1
      [units.account.signup.user(6), 5], //    2   2
      [units.account.signup.user(7), 6], //    4   4
      [units.net.enter(1), 0],
      [units.invite.confirm.tMember(5), 0],
      [units.invite.create.tMember(0), 0],
      [units.net.connetByToken(1), 4],
      [units.invite.confirm.tMember(0), 0],
      [units.invite.create.tMember(2), 0],
      [units.net.connetByToken(1), 5],
      [units.invite.confirm.tMember(2), 0],
      [units.invite.create.tMember(4), 0],
      [units.net.connetByToken(1), 6],
      [units.invite.confirm.tMember(4), 0],
      [units.net.enter(1), 1],
      [units.net.enter(1), 2],
      [units.net.enter(1), 3],
      [units.net.enter(1), 4],
      [units.net.enter(1), 5],
      [units.net.enter(1), 6],
      [units.vote.set.cMember(1), 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(2), 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(3), 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(4), 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(5), 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(2), 2],
      [units.events.vote.set, 1],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(2), 3],
      [units.events.vote.set, 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(1), 4],
      [units.events.vote.set, 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 5],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(2), 5],
      [units.events.vote.set, 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 6],
      [units.vote.set.cMember(2), 6],
      [units.events.vote.set, 1],
      [units.events.vote.set, 2],
      [units.events.vote.set, 3],
      [units.events.vote.set, 4],
      [units.events.vote.set, 5],
      [units.vote.setFinal.self, 1],
      [units.vote.check.self, 1],
      [units.events.newEvents, 2],
      [units.events.newEvents, 3],
      [units.events.newEvents, 4],
      [units.events.newEvents, 5],
      [units.events.newEvents, 6],
      [units.events.read.voteForDisvoteMember, 0],
      [units.events.read.voteForVoteMember, 1],
      [units.events.read.voteForMembers, 2],
      [units.events.read.voteForMembers, 3],
      [units.events.read.voteForMembers, 4],
      [units.events.read.voteForMembers, 5],
      [units.events.read.voteForMembers, 6],
    ],
  },
];
