import { ITestUnitsMap } from '../types/test.units.types';
import { ITestCase } from '../types/types';

export const netVoteCases = (units: ITestUnitsMap): ITestCase[] => [
  {
    title: 'Test VOTES IN NET over WS',
    dbDataFile: 'restore.sh',
    connection: 'ws',
    connCount: 7,
    caseUnits: [
      [units.account.login.user01, 0],
      [units.account.login.user02, 1],
      [units.account.login.user03, 2],
      [units.account.login.user04, 3],
      [units.account.signup.user05, 4],
      [units.account.signup.user06, 5],
      [units.account.signup.user07, 6],
      [units.net.enter.firstNet, 0],
      [units.invite.confirm.mber5, 0],
      [units.invite.create.mber0, 0],
      [units.net.connetByToken, 4],
      [units.invite.confirm.mber0, 0],
      [units.invite.create.mber2, 0],
      [units.net.connetByToken, 5],
      [units.invite.confirm.mber2, 0],
      [units.invite.create.mber4, 0],
      [units.net.connetByToken, 6],
      [units.invite.confirm.mber4, 0],
      [units.net.enter.firstNet, 1],
      [units.vote.set.mber1, 1],
      [units.vote.set.mber2, 1],
      [units.vote.set.mber3, 1],
      [units.vote.set.mber4, 1],
      [units.vote.set.mber5, 1],
      [units.net.enter.firstNet, 2],
      [units.net.enter.firstNet, 3],
      [units.net.enter.firstNet, 4],
      [units.net.enter.firstNet, 5],
      [units.net.enter.firstNet, 6],
      [units.vote.set.mber2, 2],
      [units.vote.set.mber2, 3],
      [units.vote.set.mber1, 4],
      [units.vote.set.mber2, 5],
      [units.vote.set.mber2, 6],
      [units.vote.set.self, 1],
      [units.vote.check.self, 1],
    ],
  },
];
