/* eslint-disable max-lines */
import { ITestUnitsMap } from '../types/test.units.types';
import { ITestCase } from '../types/types';

export const netVote = (units: ITestUnitsMap): ITestCase[] => [
  {
    title: 'Test VOTES IN NET 1 over WS',
    dbDataFile: 'restore.sh',
    connection: 'ws',
    caseUnits: [ //                           01  02
      [units.account.login.user(1), 0], //     x   0
      [units.account.login.user(2), 1], //     1   x
      [units.account.login.user(3), 2], //     3   3
      [units.account.login.user(4), 3], //     5   5
      [units.account.signup.user(5), 4], //    0   1
      [units.account.signup.user(6), 5], //    2   2
      [units.account.signup.user(7), 6], //    4   4
      //
      [units.net.enter(1), 0],
      [units.invite.confirm.tMember(5), 0],
      [units.events.newEvents, 3],
      [units.events.read.confirm, 3],
      [units.events.newEvents, 1],
      [units.events.read.confirmInCircle, 1],
      [units.events.newEvents, 2],
      [units.events.read.confirmInCircle, 2],
      //
      [units.invite.create.tMember(0), 0],
      [units.net.connectByToken.toNet(1), 4],
      // [units.invite.confirm.tMember(0), 0],
      // [units.events.newEvents, 4],
      // [units.events.read.confirm, 4],
      [units.events.newEvents, 0],
      [units.events.read.connectAndConfirmInTree, 0],
      [units.events.newEvents, 1],
      [units.events.read.connectAndConfirmInCircle, 1],
      [units.events.newEvents, 2],
      [units.events.read.connectAndConfirmInCircle, 2],
      [units.events.newEvents, 3],
      [units.events.read.connectAndConfirmInCircle, 3],
      //
      [units.invite.create.tMember(2), 0],
      [units.net.connectByToken.toNet(1), 5],
      [units.events.newEvents, 0],
      [units.events.read.connectAndConfirmInTree, 0],
      // [units.invite.confirm.tMember(2), 0],
      // [units.events.newEvents, 5],
      // [units.events.read.confirm, 5],
      [units.events.newEvents, 1],
      [units.events.read.connectAndConfirmInCircle, 1],
      [units.events.newEvents, 2],
      [units.events.read.connectAndConfirmInCircle, 2],
      [units.events.newEvents, 3],
      [units.events.read.connectAndConfirmInCircle, 3],
      [units.events.newEvents, 4],
      [units.events.read.connectAndConfirmInCircle, 4],
      //
      [units.invite.create.tMember(4), 0],
      [units.net.connectByToken.toNet(1), 6],
      [units.events.newEvents, 0],
      [units.events.read.connectAndConfirmInTree, 0],
      // [units.invite.confirm.tMember(4), 0],
      // [units.events.newEvents, 6],
      // [units.events.read.confirm, 6],
      [units.events.newEvents, 1],
      [units.events.read.connectAndConfirmInCircle, 1],
      [units.events.newEvents, 2],
      [units.events.read.connectAndConfirmInCircle, 2],
      [units.events.newEvents, 3],
      [units.events.read.connectAndConfirmInCircle, 3],
      [units.events.newEvents, 4],
      [units.events.read.connectAndConfirmInCircle, 4],
      [units.events.newEvents, 5],
      [units.events.read.connectAndConfirmInCircle, 5],
      //
      [units.net.enter(1), 1],
      [units.net.enter(1), 2],
      [units.net.enter(1), 3],
      [units.net.enter(1), 4],
      [units.net.enter(1), 5],
      [units.net.enter(1), 6],
      //
      [units.vote.set.cMember(1), 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(2), 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(3), 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(4), 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(5), 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(2), 2],
      [units.events.instant.vote, 1],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(2), 3],
      [units.events.instant.vote, 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(1), 4],
      [units.events.instant.vote, 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 5],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(2), 5],
      [units.events.instant.vote, 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 6],
      //
      [units.vote.set.cMember(2), 6],
      [units.events.instant.vote, 1],
      [units.events.instant.vote, 2],
      [units.events.instant.vote, 3],
      [units.events.instant.vote, 4],
      [units.events.instant.vote, 5],
      [units.vote.setFinal.self, 1],
      [units.vote.check.self, 1],
      [units.events.newEvents, 2],
      [units.events.newEvents, 3],
      [units.events.newEvents, 4],
      [units.events.newEvents, 5],
      [units.events.newEvents, 6],
      [units.events.read.vote.forDisvoteMember, 0],
      [units.events.read.vote.forVoteMember, 1],
      [units.events.read.vote.forMembers, 2],
      [units.events.read.vote.forMembers, 3],
      [units.events.read.vote.forMembers, 4],
      [units.events.read.vote.forMembers, 5],
      [units.events.read.vote.forMembers, 6],
      [units.events.check.confirmed, 0],
      [units.net.get.structure(1), 0],
    ],
  },
];
