CREATE ROLE merega;
ALTER ROLE merega WITH LOGIN PASSWORD 'merega' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE merega OWNER merega;
REVOKE ALL ON DATABASE merega FROM PUBLIC;
GRANT CONNECT ON DATABASE merega TO merega;
GRANT ALL ON DATABASE merega TO merega;