Table "nodes" {
  "node_id" bigint [primary key, not null]
  "node_level" integer [not null, default: 0]
  "node_position" integer [not null, default: 0]
  "parent_node_id" bigint [default: NULL]
  "net_id" bigint [not null]
  "count_of_members" integer [not null, default: 0]
  "updated" timestamp [not null, default: 'now()']
  Indexes {
    (node_id, net_id) [unique, name: "uk_nodes_node_net"]
    (node_id, parent_node_id) [unique, name: "uk_nodes_node_parent_node"]
  }
}

Table "nets" {
  "net_id" bigint [primary key, not null]
  "net_level" integer [not null, default: 0]
  "parent_net_id" bigint [default: NULL]
  "first_net_id" bigint [not null]
  "count_of_nets" integer [not null, default: 1]
}

Table "users" {
  "user_id" bigint [primary key, not null]
  "email" "character varying(50)" [not null]
  "name" "character varying(50)" [default: NULL]
  "mobile" "character varying(50)" [default: NULL]
  "password" "character varying(255)" [default: NULL]
  "confirmed" boolean [not null, default: false]
  Indexes {
    email [type: btree, unique, name: "users_email_idx"]
  }
}

Table "nets_data" {
  "net_id" bigint [primary key, not null]
  "name" "character varying(50)" [not null]
  "goal" text [default: NULL]
  "resource_name" "character varying(50)" [default: NULL]
  "resource_link" "character varying(255)" [default: NULL]
}

Table "members" {
  "member_id" bigint [primary key, not null]
  "node_id" bigint [not null]
  "net_id" bigint [not null]
  "user_id" bigint [not null]
  "email_show" boolean [not null, default: false]
  "name_show" boolean [not null, default: false]
  "mobile_show" boolean [not null, default: false]
  "confirmed" boolean [not null, default: false]
  "active_date" timestamp [not null, default: 'now()']
  Indexes {
    node_id [unique, name: "uk_members_node"]
    (user_id, net_id) [unique, name: "uk_members_user_net"]
    // (user_id, node_id) [unique, name: "uk_members_user_node"]
  }
}

Table "members_tmp" {
  "member_id" bigint [primary key, not null]
  "node_id" bigint [not null]
  "net_id" bigint [not null]
  "user_id" bigint [not null]
  "email_show" boolean [not null]
  "name_show" boolean [not null]
  "mobile_show" boolean [not null]
  "confirmed" boolean [not null]
  "active_date" timestamp [not null]
}

Table "users_tokens" {
  "user_id" bigint [primary key, not null]
  "token" "character varying(255)" [not null]
  Indexes {
    token [type: btree, unique, name: "uk_users_tokens_token_idx"]
  }
}

Table "nodes_invites" {
  "parent_node_id" bigint [not null]
  "node_id" bigint [primary key, not null]
  "member_name" "character varying(50)" [not null]
  "token" "character varying(255)" [not null]
  Indexes {
    token [type: btree, unique, name: "uk_nodes_invites_token_idx"]
  }
}

Table "events" {
  "event_id" bigint [primary key, not null]
  "member_node_id" bigint [default: NULL]
  "user_id" bigint [not null]
  "user_node_id" bigint [default: NULL]
  "net_view" "character(10)" [not null]
  "message" "character varying(255)" [not null]
  "date" timestamp [not null]
  Indexes {
    user_id [name: "sk_events_user"]
  }
}

Table "users_board_messages" {
  "message_id" bigint [primary key, not null]
  "net_id" bigint [not null]
  "user_id" bigint [not null]
  "node_id" bigint [not null]
  "net_view" "character(10)" [not null, default: 'net']
  "message" "character varying(255)" [not null]
  "date" timestamp [not null, default: 'now()']
  Indexes {
    net_id [name: "sk_users_board_messages_net"]
    (user_id, net_id) [unique, name: "uk_users_board_mesages_user_net"]
  }
}

Table "events_tmp" {
  "event_id" bigint [primary key, not null]
  "user_id" bigint [not null]
  "user_node_id" bigint [not null]
  "net_view" "character(10)" [not null]
  "member_node_id" bigint [default: NULL]
  "message" "character varying(255)" [not null]
  "date" timestamp [not null]
  Indexes {
    user_id [name: "sk_events_tmp_user"]
  }
}

Table "users_changes" {
  "user_id" bigint [primary key, not null]
  "date" timestamp [not null]
}

Table "users_members" {
  "parent_node_id" bigint [not null]
  "user_id" bigint [not null]
  "member_id" bigint [not null]
  "dislike" boolean [not null, default: false]
  "vote" boolean [not null, default: false]
  Indexes {
    (parent_node_id, user_id, member_id) [pk]
  }
}

Table "sessions" {
  "session_id" bigint [primary key, not null]
  "user_id" bigint [not null]
  "session_key" "character varying(255)" [not null]
  "session_value" "character varying(255)" [not null]
  "updated" timestamp [not null, default: 'now()']
}

Ref "fk_nodes_net":"nets"."net_id" < "nodes"."net_id" [delete: cascade]
Ref "fk_nets_data_net":"nets"."net_id" - "nets_data"."net_id" [delete: cascade]
Ref "fk_members_node_net":"nodes".(node_id,net_id) - "members".(node_id, net_id)
Ref "fk_members_user":"users"."user_id" < "members"."user_id" [delete: cascade]
Ref "fk_nodes_invites_node_parent_node":"nodes".(node_id, parent_node_id) - "nodes_invites".(node_id, parent_node_id) [update: cascade]
Ref "fk_nodes_invites_parent_user_node":"members"."node_id" < "nodes_invites"."parent_node_id" [delete: cascade]
Ref "fk_users_tokens_user":"users"."user_id" < "users_tokens"."user_id" [delete: cascade]
Ref "fk_users_members_parent_node":"nodes"."node_id" < "users_members"."parent_node_id"
Ref "fk_users_members_user":"users"."user_id" < "users_members"."user_id" [delete: cascade]
Ref "fk_users_members_member":"users"."user_id" < "users_members"."member_id" [delete: cascade]
Ref "fk_sessions_user":"users"."user_id" < "sessions"."user_id" [delete: cascade]
Ref "fk_events_user": "users"."user_id" < "events"."user_id" [delete: cascade]
Ref "fk_events_user_node": "members"."node_id" < "events"."user_node_id" [update: set null]
Ref "fk_events_member_node": "nodes"."node_id" < "events"."member_node_id" [delete: cascade]
Ref "fk_users_changes_user": "users"."user_id" - "users_changes"."user_id" [delete: cascade]
// Ref "fk_users_board_messages_user_node":"nets_users".(user_id, node_id) - "users_board_messages".(user_id, node_id) [update: cascade, delete: cascade]
Ref "fk_users_board_messages_node_net":"nodes".(node_id, net_id) - "users_board_messages".(node_id, net_id) [delete: cascade]
