DROP TABLE IF EXISTS nets_data CASCADE;
DROP TABLE IF EXISTS nets_users_data CASCADE;
DROP TABLE IF EXISTS users_nodes_invites CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS nodes CASCADE;
DROP TABLE IF EXISTS nets CASCADE;
